name: Build
on:
  pull_request:
  push:
    branches:
      - dev
jobs:
  android:
    runs-on: ubuntu-latest
    container: gradle:8.5.0-jdk17
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gradle-cache
      - uses: android-actions/setup-android@v3.2.0
      - uses: ./.github/actions/firebase-google-service
        with:
          secret: ${{ secrets.FIREBASE_GOOGLE_SERVICE }}
      - run: ./gradlew assembleDebug
      - uses: ./.github/actions/firebase-service-credentials
        with:
          secret: ${{ secrets.FIREBASE_SERVICE_CREDENTIALS }}
      - run: ./gradlew appDistributionUploadDebug
        if: github.ref == 'refs/heads/dev'
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - run: xcodebuild -configuration Debug -sdk iphonesimulator16.2
        working-directory: iosApp
