name: Build
on:
  pull_request:
  push:
    branches:
      - dev
jobs:
  android-x:
    runs-on: ubuntu-latest
    container: gradle:8.5.0-jdk17
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gradle-cache
      - uses: android-actions/setup-android@v3.2.0
      - uses: ./.github/actions/firebase-google-service
        with:
          secret: ${{ secrets.FIREBASE_GOOGLE_SERVICE }}
      - run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: android-debug
          path: androidApp/build/outputs/apk/debug/*.apk
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: ./.github/actions/gradle-cache
      - run: echo ${{ secrets.GOOGLE_SERVICE_IOS }} > iosApp/picover/GoogleService-Info.plist
      - run: xcodebuild -scheme Picover -configuration Debug -sdk iphonesimulator16.2 build
        working-directory: iosApp
