name: Tests
on:
  pull_request:
  push:
    branches:
      - dev
jobs:
  android:
    strategy:
      matrix:
        task: ['androidApp:koverHtmlReportDebug', 'ktlint-ruleset:test', 'lint:test']
    runs-on: ubuntu-latest
    container: gradle:8.8.0-jdk17
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gradle-cache
      - uses: android-actions/setup-android@v3.2.1
      - uses: ./.github/actions/firebase-google-service
        with:
          secret: ${{ secrets.FIREBASE_GOOGLE_SERVICE }}
      - run: ./gradlew ${{ matrix.task }}
  ios:
    runs-on: macos-latest
    if: ${{ false }} # run unit tests from iosApp
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - run: ./gradlew shared:iosX64Test
