name: Tests
on:
  pull_request:
  push:
    branches:
      - dev
jobs:
  test:
    strategy:
      matrix:
        task: ["app:koverHtmlReportDebug", "ktlint-ruleset:test", "lint:test"]
    runs-on: ubuntu-latest
    container: gradle:8.4.0-jdk17
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gradle-cache
      - uses: android-actions/setup-android@v3.1.0
      - uses: ./.github/actions/firebase-google-service
        with:
          secret: ${{ secrets.FIREBASE_GOOGLE_SERVICE }}
      - run: ./gradlew ${{ matrix.task }}
